### ISSUE TITLE
getting started page typo

### ISSUE THREAD

**Issue by NathanTe** [Kr0san89/ng-click-outside#13]
You say import `Add ClickOutsideModule to your list of module imports:` but the code sample beneath adds `NgClickOutsideDirective`.

Can anyone confirm this package works for angular 15?

**Comment by NathanTe** [comment]
works on angular 15 maybe add to compatibility table :)

**Comment by Kr0san89** [comment]
Thanks will update the Readme.
ng15 works and likely ng16 as well. Don't see any breaking changes affecting the library
