### ISSUE TITLE
Click outside and ngIf

### ISSUE THREAD

**Issue by filippomuscolino** [Kr0san89/ng-click-outside#28]
Hi,
I have a problem with an element inside an *ngIf: click outside is triggered when element has already been removed from DOM.
I already read the thread on the original repo, but `delayClickOutsideInit` property didn't work for me.
I was thinking about adding an extra check in `shouldExclude` function (something like `document.contains(target)`), so that if target has been removed from DOM then element is excluded.
Do you think is feasible to add this?

Thanks!

**Comment by Kr0san89** [comment]
Hello,

i think `delayClickOutsideInit` handles a different use-case where you want not get imdiatly the outside click events but after that delay.

As the directive is cleaning up the eventlisteners in the ngOnDestroy it should be fine and i tried it just now with  added into the code here in app.component.html (which is the demo app in this repo)
```
<div
  (click)="onClick($event)"
  (clickOutside)="onClickedOutside($event)"
  [attachOutsideOnClick]="attachOutsideOnClick"
  [clickOutsideEnabled]="enabled"
  *ngIf="countInside < 2"
  [emitOnBlur]="true">
  <p>Clicked inside: {{countInside}}</p>
  <p>Clicked outside: {{countOutside}}</p>

  <label>
    <input type="checkbox" [checked]="attachOutsideOnClick" (click)="_toggleAttachOutsideOnClick()" />
    <span>Attach on click</span>
  </label>

  <label>
    <input type="checkbox" [checked]="enabled" (click)="_toggleEnabled()" />
    <span>Enabled</span>
  </label>
</div>
```
When you click 2 times inside the listener get's destroyed and furthermore there are no events coming from clickOustside (breakpoint into the directive _emit function). So looks fine to me.

i would assume there is something wrong with the distruction of the element you have bound it to. 
Can you bring an example where this issue arises?

The extra function you can easily (if needed) be add to your code if the directive emit's you get the event and can simple check the condition of the `*ngIf`. 

Hope this helps 
kind regards

**Comment by Kr0san89** [comment]
don't see any issue from the lib, when further information is provided you can reopen
