### ISSUE TITLE
`clickOutsideExclude` isn't working, but just `exclude` is?

### ISSUE THREAD

**Issue by Sefibrah** [Kr0san89/ng-click-outside#46]
It's just as the title says, when I installed 11.0.0. version, and I get the error from the title. So, what's up with that?

**Comment by Kr0san89** [comment]
Hello, 

yes that's right on version 11 it was `exclude` see readme of version 11
https://github.com/Kr0san89/ng-click-outside/blob/v11.0.0/README.md or https://www.npmjs.com/package/ng-click-outside2/v/11.0.0
Was changed in version 13 to `clickOutsideExclude` as it got extracted as Directive for better tree-shaking. (smaller bundle if not used)
