### ISSUE TITLE
clickOutsideExclude property not working

### ISSUE THREAD

**Issue by matusko89** [Kr0san89/ng-click-outside#48]
Hey, I just upgraded to Angular 17 and to ng-click-outside v13.0.0
I used the exclude option in the previos 11.0.0 version.
I used the new directive and used the clickOutsideExclude property but no mather what I tried I always get an error:
Can't bind to 'clickOutsideExclude' since it isn't a known property of 'div'.

I created a stackblits with reproduction
https://stackblitz-starters-u2pnnl.stackblitz.io

**Comment by matusko89** [comment]
Hmmm I just closely read the comment in #46 and just to clarify so I should use clickOutsideExclude as directive with * clickOutsideExclude right? In this case it should be appropriate to update the docs

**Comment by Kr0san89** [comment]
Hello, 

the readme states that https://github.com/Kr0san89/ng-click-outside/blob/master/README.md 
I also marked it as breaking change in the release https://github.com/Kr0san89/ng-click-outside/releases/tag/v13.0.0

If you have tips to improve that part in the documentation please give me a hint

thanks

**Comment by matusko89** [comment]
Hi,
I would change the description part of the readme so the example in there would be: `*clickOutsideExclude="'button,.btn-primary'"`
This would make it much clearer :)
