### ISSUE TITLE
delayClickOutsideInit not working as expected after update to v15

### ISSUE THREAD

**Issue by Kramy** [Kr0san89/ng-click-outside#63]
After update from 14.0.1 to 15.0.0, delayClickOutsideInit stopped working.

### Minor description:
1. There is a for-loop printing an array in template.
2. Each array item has css class="style", clickOutside directive and also exclude="style" and delay=true directives.
3. Clicking "Add" button adds a new item into the array.
4. Clicking outside removes items from template.

In v14 it works fine, once you click "Add" button, a new item is added and no clickOutside is triggered.

In v15 clickOutside is triggered immediately (ignoring delay) so no item is printed (is removed immediately after been added).

[Stackblitz example](https://stackblitz.com/edit/stackblitz-starters-fwug2u?file=package.json)

**Comment by Kr0san89** [comment]
did you add the new directive `NgClickOutsideDelayOutsideDirective`see release notes https://github.com/Kr0san89/ng-click-outside/releases/tag/v15.0.0
most people will not need that delay but still have it in there code this is why i splitted it out.

kind regards

**Comment by Kramy** [comment]
Yes, i did. If you look at the example, both imports are commented. Just have to install v15 and uncomment imports to test v15.

**Comment by Kr0san89** [comment]
ah thanks for the good example :)

you are right. should be fixed with https://github.com/Kr0san89/ng-click-outside/pull/64 and version 15.0.1

sorry for the bug -.-

**Comment by Kramy** [comment]
Nice! Thanks for the quick fix.

Working in v15.0.1.
