### ISSUE TITLE
False positive test case in ng-click-outside-delay-outside.directive.spec.ts

### ISSUE THREAD

**Issue by VitaliiLitkevichVL** [Kr0san89/ng-click-outside#82]
When I remove clickOutsideButton2 = clickOutsideButton2 + 1 from the template, the test still passes.
clickOutside output doesn't call

**Comment by Kr0san89** [comment]
Hello,

it is true when you remove that it still passes. But that is not what the test tries to test. (the "normal" case is alreay tested in ng-click-outside.directive.spec.ts)
It should test this delay directive, which in fact should not fire imediate.

If you look into the Comment & Git History you acuallty can find it's purpose.
https://github.com/Kr0san89/ng-click-outside/pull/64
https://github.com/Kr0san89/ng-click-outside/issues/63

I think there are other  ways with fakeAsync to improve the test, but for now i would say it is fine.

Hope this helps.

**Comment by Kr0san89** [comment]
as there was no futher comment, i will close the issue for now
